sudo: required
services:
    - docker

before_install:
    - docker build -t hlinus/docker-react -f Dockerfile.dev .

script:
    - docker run hlinus/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-354938325680"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"